### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by awakekat** [santip/swap-panes#1]
Uncaught TypeError: Cannot read property '0' of undefined

**Atom Version**: 0.155.0
**System**: Mac OS X 10.10.1
**Thrown From**: [swap-panes](https://github.com/santip/swap-panes) package, v0.1.0
### Steps To Reproduce
1. ...
2. ...
### Stack Trace

```
At /Users/katwake/.atom/packages/swap-panes/lib/swap-panes.coffee:31

TypeError: Cannot read property '0' of undefined
  at Object.module.exports.swap (/Users/katwake/.atom/packages/swap-panes/lib/swap-panes.coffee:31:6)
  at Object.module.exports.swapLeft (/Users/katwake/.atom/packages/swap-panes/lib/swap-panes.coffee:12:17)
  at atom-workspace.<anonymous> (/Users/katwake/.atom/packages/swap-panes/lib/swap-panes.coffee:5:60)
  at atom-workspace.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:167:20)

```

/cc @atom/core

**Comment by awakekat** [comment]
Just installed this. Hit the key binding and error showed up. Swapping the the right if that helps.

**Comment by wjn** [comment]
unfortunately, this has been my experience as well.
